from mage_ai.errors.base import MageBaseException


class FileExistsError(MageBaseException):
    pass
